'use client';
import { type FormEvent, useEffect, useRef, useState } from 'react';
import { Link } from '@/lib/next-router-compat';
import { Loader2, Send, Sparkles, Trash2 } from 'lucide-react';
import { AssistantError, clearChatHistory, loadChatHistory, sendMessage } from '@/api/integrated-ai-api';
import type { ChatMessage } from '@/api/integrated-ai-api';
import pb from '@/lib/pocketbase-client';
import { requireAuth } from '@/lib/require-auth';



export function HydrateFallback() {
	return <div className="min-h-[60dvh] bg-sky-50" />;
}

export default function AvaPage() {
	const [messages, setMessages] = useState<ChatMessage[]>([]);
	const [input, setInput] = useState('');
	const [isStreaming, setIsStreaming] = useState(false);
	const [error, setError] = useState<{ message: string; status?: number } | null>(null);
	const bottomRef = useRef<HTMLDivElement>(null);

	useEffect(() => {
		loadChatHistory().then(setMessages).catch(() => setMessages([]));
	}, []);

	useEffect(() => {
		bottomRef.current?.scrollIntoView({ behavior: 'smooth' });
	}, [messages]);

	const send = async (event: FormEvent) => {
		event.preventDefault();
		const text = input.trim();
		if (!text || isStreaming) return;

		setError(null);
		setInput('');
		setMessages(previous => [...previous, { role: 'user', content: text }, { role: 'assistant', content: '' }]);
		setIsStreaming(true);

		try {
			await sendMessage({
				text,
				onText: chunk => setMessages((previous) => {
					const next = [...previous];
					const last = next[next.length - 1];
					next[next.length - 1] = { ...last, content: last.content + chunk };

					return next;
				}),
			});
		} catch (err) {
			setMessages(previous => previous.slice(0, -1));

			if (err instanceof AssistantError) {
				setError({ message: err.message, status: err.status });
			} else if (!(err instanceof Error && err.name === 'AbortError')) {
				setError({ message: 'AVA could not answer right now — try again.' });
			}
		} finally {
			setIsStreaming(false);
		}
	};

	const clear = async () => {
		await clearChatHistory().catch(() => {});
		setMessages([]);
	};

	return (
		<div className="bg-sky-50 py-10 lg:py-14">
			<div className="mx-auto flex max-w-3xl flex-col px-4 lg:px-6" style={{ minHeight: '70dvh' }}>
				<div className="flex items-center justify-between">
					<div className="flex items-center gap-3">
						<span className="flex size-11 items-center justify-center rounded-2xl bg-[#0A1B36]">
							<Sparkles className="size-5 text-[#38C3FF]" />
						</span>
						<div>
							<h1 className="text-2xl font-semibold text-[#0B1F3A]">AVA</h1>
							<p className="text-sm text-[#5B6B7F]">Your AI assistant for booking layouts, pricing, and growth.</p>
						</div>
					</div>
					<button type="button" onClick={clear} className="flex h-10 items-center gap-2 rounded-xl border border-[#D1D6D9] bg-white px-4 text-sm font-medium text-[#5B6B7F] hover:border-[#0E63B0]">
						<Trash2 className="size-4" />
						New session
					</button>
				</div>

				<div className="mt-6 flex-1 space-y-4 overflow-y-auto rounded-3xl border border-[#E4ECF3] bg-white p-5">
					{messages.length === 0 ? (
						<div className="flex h-full flex-col items-center justify-center py-16 text-center">
							<Sparkles className="size-8 text-[#38C3FF]" />
							<p className="mt-4 max-w-sm text-[15px] text-[#5B6B7F]">
								Ask AVA to draft a booking page layout, suggest service prices, write your bio, or plan a promotion.
							</p>
						</div>
					) : (
						messages.map((message, index) => (
							<div key={index} className={`flex ${message.role === 'user' ? 'justify-end' : 'justify-start'}`}>
								<div className={`max-w-[80%] rounded-2xl px-4 py-3 text-[15px] leading-6 whitespace-pre-wrap ${message.role === 'user' ? 'bg-[#0E63B0] text-white' : 'bg-sky-50 text-[#0B1F3A]'}`}>
									{message.content}
									{message.role === 'assistant' && isStreaming && index === messages.length - 1 ? (
										<span className="ml-1 inline-block size-2 animate-pulse rounded-full bg-[#0E63B0]" />
									) : null}
									{message.images?.map(url => (
										<img key={url} src={url} alt="Generated by AVA" className="mt-3 rounded-xl" />
									))}
								</div>
							</div>
						))
					)}
					<div ref={bottomRef} />
				</div>

				{error ? (
					<div className="mt-4 rounded-2xl bg-red-50 px-5 py-4 text-sm text-red-700">
						{error.message}
						{error.status === 401 ? <> <Link to="/login" className="font-semibold underline">Sign in</Link></> : null}
						{error.status === 403 ? (
							<button
								type="button"
								className="ml-2 font-semibold underline"
								onClick={() => { const email = pb.authStore.record?.email; if (email) void pb.collection('users').requestVerification(email); }}
							>
								Resend verification email
							</button>
						) : null}
					</div>
				) : null}

				<form onSubmit={send} className="mt-4 flex gap-3">
					<input
						value={input}
						onChange={event => setInput(event.target.value)}
						placeholder="Ask AVA anything about your booking business…"
						className="h-13 flex-1 rounded-2xl border border-[#D1D6D9] bg-white px-5 text-[15px] outline-none focus:border-[#0E63B0] focus:ring-2 focus:ring-[#0E63B0]/20"
					/>
					<button
						type="submit"
						disabled={isStreaming || !input.trim()}
						className="flex h-13 w-13 items-center justify-center rounded-2xl bg-[#0E63B0] text-white transition-colors hover:bg-[#0d5a9e] disabled:opacity-50"
						aria-label="Send message"
					>
						{isStreaming ? <Loader2 className="size-5 animate-spin" /> : <Send className="size-5" />}
					</button>
				</form>
			</div>
		</div>
	);
}
