'use client';
import { ArrowRight, Check, CreditCard, ShieldCheck, Sparkles } from 'lucide-react';
import { Link } from '@/lib/next-router-compat';


const INCLUDED = ['Unlimited services and booking pages', 'Flexible weekly schedules and service durations', 'Client profiles, appointment history, and inbox', 'Email and SMS booking confirmations', 'Estimated queue time for customers', 'Provider dashboard with revenue and booking insights', 'Secure payment options and booking records', 'Admin support for your growing business'];

export default function PricingPage() {
	return (
		<div className="bg-[#F6FBFC]">
			<section className="px-4 py-20 text-center lg:px-6 lg:py-28"><div className="mx-auto max-w-3xl"><div className="mx-auto flex size-12 items-center justify-center rounded-xl bg-[#0A1B36] text-[#38C3FF]"><Sparkles className="size-6" /></div><p className="mt-6 text-sm font-semibold tracking-[0.16em] text-[#0E63B0] uppercase">Simple monthly pricing</p><h1 className="mt-4 text-4xl leading-tight font-semibold text-[#0B1F3A] sm:text-5xl lg:text-6xl">Everything your service business needs. One plan.</h1><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-[#5B6B7F]">No feature maze. No per-service upgrade. Subscribe once and get the complete ReserveMe toolkit for your industry.</p></div></section>
			<section className="px-4 pb-20 lg:px-6 lg:pb-28"><div className="mx-auto max-w-5xl"><div className="overflow-hidden rounded-3xl border border-[#BFDDE4] bg-white shadow-[0_20px_60px_rgba(16,24,40,0.1)]"><div className="grid lg:grid-cols-[0.85fr_1.15fr]"><div className="bg-[#0A1B36] p-8 text-white sm:p-10"><p className="text-sm font-semibold tracking-[0.16em] text-[#38C3FF] uppercase">The complete plan</p><h2 className="mt-5 text-3xl font-semibold">ReserveMe Pro</h2><p className="mt-3 text-[15px] leading-6 text-white/70">One subscription for every service provider, whether you are starting solo or running a growing team.</p><div className="mt-10 flex items-end gap-2"><span className="text-6xl font-semibold tracking-tight">$29</span><span className="pb-2 text-white/60">/ month</span></div><p className="mt-2 text-sm text-white/60">Cancel anytime. No long-term contract.</p><Link to="/signup" className="mt-8 inline-flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#38C3FF] px-5 font-semibold text-[#0A1B36] hover:bg-white">Start your free account <ArrowRight className="size-4" /></Link><div className="mt-6 flex items-center gap-2 text-sm text-white/60"><ShieldCheck className="size-4 text-[#38C3FF]" /> Secure account and booking data</div></div><div className="p-8 sm:p-10"><h3 className="text-xl font-semibold text-[#0B1F3A]">Everything included</h3><p className="mt-2 text-[15px] text-[#5B6B7F]">The tools you need to run the customer journey from first click to confirmed appointment.</p><ul className="mt-7 grid gap-4 sm:grid-cols-2">{INCLUDED.map(item => <li key={item} className="flex gap-3 text-[15px] leading-6 text-[#4A5B6C]"><Check className="mt-0.5 size-5 shrink-0 text-[#0E63B0]" />{item}</li>)}</ul><div className="mt-9 border-t border-[#E4ECF3] pt-6"><div className="flex items-start gap-3"><CreditCard className="mt-0.5 size-5 text-[#0E63B0]" /><div><p className="font-semibold text-[#0B1F3A]">Built for predictable growth</p><p className="mt-1 text-sm leading-6 text-[#5B6B7F]">Keep your plan as your service menu grows. Your price stays the same while your business gets more capable.</p></div></div></div></div></div></div></div></section>
			<section className="border-t border-[#DCECEF] bg-white px-4 py-16 lg:px-6"><div className="mx-auto max-w-3xl text-center"><h2 className="text-3xl font-semibold text-[#0B1F3A]">Ready to make booking easier?</h2><p className="mt-4 text-[17px] text-[#5B6B7F]">Set up your service page, choose your hours, and start accepting appointments.</p><Link to="/signup" className="mt-7 inline-flex h-12 items-center gap-2 rounded-xl bg-[#0E63B0] px-7 font-semibold text-white hover:bg-[#0d5a9e]">Get started <ArrowRight className="size-4" /></Link></div></section>
		</div>
	);
}
